INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
1, 'January', 31); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
2, 'February', 29); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
3, 'March', 31); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
4, 'April', 30); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
5, 'May', 31); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
6, 'June', 30); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
6, 'June', 30); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
6, 'June', 30); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
8, 'August', 31); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
9, 'September', 30); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
11, 'November', 30); 
INSERT INTO TB_MONTH ( SLNO, MONTH_NAME, MONTH_DAY ) VALUES ( 
12, 'December', 31); 
commit;
 
